# Generated by Django 5.0.6 on 2024-05-17 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('dex_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTyping',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stathp', models.IntegerField()),
                ('statatk', models.IntegerField()),
                ('statdef', models.IntegerField()),
                ('statspa', models.IntegerField()),
                ('statspd', models.IntegerField()),
                ('statspe', models.IntegerField()),
                ('form_num', models.IntegerField(null=True)),
                ('ability1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_abil1', to='app_pokedata.pokemonability')),
                ('ability2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_abil2', to='app_pokedata.pokemonability')),
                ('abilityhidden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_abil_hidden', to='app_pokedata.pokemonability')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pokedata.pokemonspecies')),
                ('type1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_type1', to='app_pokedata.pokemontyping')),
                ('type2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_type2', to='app_pokedata.pokemontyping')),
            ],
        ),
        migrations.CreateModel(
            name='PokedexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pokedata.pokemon')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pokedata.pokemongame')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTypingEffectiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness', models.DecimalField(choices=[(1.0, 'Effective'), (2.0, 'Super Effective'), (0.5, 'Not Very Effective'), (0.0, 'No Effect')], decimal_places=1, max_digits=2)),
                ('attacking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_type', to='app_pokedata.pokemontyping')),
                ('defending_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_type', to='app_pokedata.pokemontyping')),
            ],
        ),
    ]
